name: a2c  # algorithm name

a2c:
  policy: "CnnPolicy"               # Policy model to use (MlpPolicy, CnnPolicy, ...)
  policy_kwargs: {}                 # Additional arguments for policy model
  
  learning_rate: 0.001              # Learning rate for A2C
  n_steps: 32                       # Number of steps in rollout
  gamma: 0.99                       # Discount factor
  gae_lambda: 0.95                  # GAE (Generalized Advantage Estimation) lambda
  ent_coef: 0.05                    # Entropy coefficient
  vf_coef: 0.5                      # Value function coefficient
  max_grad_norm: 0.5                # Max norm for gradient clipping
  rms_prop_eps: 1e-5                # Epsilon for RMSProp optimizer
  use_rms_prop: true                # Use RMSProp optimizer
  use_sde: false                    # Use State Dependent Exploration (SDE)
  sde_sample_freq: -1               # SDE sampling frequency
  normalize_advantage: true         # Normalize advantage estimates
  verbose: 1                        # Verbosity level