
name: a3c  # algorithm name

# A3C Algorithm settings
algorithm:
  lr: 0.0001  # learning rate for policy model
  blocker_model_lr: 0.001  # learning rate for blocker model
  gamma: 0.99  # discount factor for rewards
  gae_lambda: 1.00  # lambda for GAE
  entropy_coef: 0.01  # entropy term coefficient
  value_loss_coef: 0.5  # value loss coefficient
  max_grad_norm: 50  # maximum gradient norm
  num_steps: 20  # number of forward steps in A3C
  max_episode_length: 1000000  # maximum length of an episode
  max_steps: 3000000  # maximum number of steps to train
  max_steps_for_blocker_training: 100000  # maximum steps for blocker model training
  alpha: 0.01  # coefficient for blocker model Entropy
  beta: 0.01  # coefficient for disagreement between blocker model and human expert
  num_processes: 10  # number of training processes
  no_shared: False  # use optimizer without shared momentum
