device: cuda
exp_name: intervention_rl

seed: 42
exp_type: "none"                  # Type of methods (none, expert, ours, hirl)
pretrained_blocker: null          # Path to pretrained blocker weights (if any)

train:
  save_model: True
  save_blocker_model: True
  save_blocker_dataset: False

eval:
  eval_seed: 20                     # Seed for evaluation
  eval_episodes: 5                  # Number of episodes to evaluate
  verbose: 1

hp_name: e-${env.short_name}_a-${algo.name}_et-${exp_type}_ent-${algo[${algo.name}].ent_coef}_al-${env.alpha}_be-${env.beta}_io-${env.iota}_s-${seed}

wandb:
  use: True
  project: modified_hirl
  name: intervention_rl_${hp_name}
  entity: intervention_rl

defaults:
  - _self_
  - env: pong
  - algo: a2c
  - override hydra/job_logging: disabled
  # - override hydra/launcher: local

hydra:
  job:
    name: ${hp_name}  
    chdir: False

  output_subdir: null
  run:
    dir: results/${hp_name}/${now:%Y-%m-%d}-${now:%H-%M-%S}
  
  sweep:
    dir: results/${now:%Y-%m-%d}-${now:%H-%M-%S}
    subdir: ${hp_name}